import type { NextProxyConfig } from "./types/next-proxy-config.js";

export function defineNextProxyConfig(config: NextProxyConfig) {
  return config;
}

export function createNextProxy() {
  return (request: any) => {
    // Middleware logic will be generated by the CLI
    return;
  };
}

export * from "./utils/auth.js";
export * from "./types/next-proxy-config.js";
export * from "./types/route-rule.js";
export * from "./types/role-config.js";
export * from "./types/acess-type.js";
export * from "./types/route-matcher.js";